<?php if ($this->getReviewsCount()): ?>
    <div class="rating">
        <?php if ($this->getRatingSummary()):?>
        <div class="rating__stars">
            <div class="rating__negative">
                <?php for($i=0;$i<5;$i++) : ?>
                <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'star-full'); ?>
                <?php endfor; ?>
            </div>
            <div class="rating__positive" style="width:<?php echo $this->getRatingSummary() ?>%">
                <?php for($i=0;$i<5;$i++) : ?>
                <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'star-full'); ?>
                <?php endfor; ?>
            </div>
        </div>
        <?php endif;?>
        <div class="rating__num micro">
            <a href="<?php echo $this->getReviewsUrl() ?>" rel="nofollow"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
        </div>
    </div>
<?php endif; ?>
