<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating rating-box">
                <div class="rating__stars">
                    <div class="rating__negative">
                        <?php for($i=0;$i<5;$i++) : ?>
                            <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'star-full'); ?>
                        <?php endfor; ?>
                    </div>
                    <div class="rating__positive" style="width: <?php echo $this->getRatingSummary() ?>%;">
                        <?php for($i=0;$i<5;$i++) : ?>
                            <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'star-full'); ?>
                        <?php endfor; ?>
                    </div>
                </div>
                
                <div class="rating__num micro">
                    <a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
                </div>
                    
            </div>
        <?php endif;?>
        
    </div>

<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>
