<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Product Reviews') ?></h1>
</div>
<?php if( $this->getCollection() && $this->count()): ?>
    <?php echo $this->getToolbarHtml() ?>
    <table class="data-table" id="my-reviews-table">
        <thead>
            <th><?php echo $this->__('Review Date'); ?></th>
            <th><?php echo $this->__('Product Name'); ?></th>
            <th><?php echo $this->__('Star Rating'); ?></th>
            <th><?php echo $this->__('Review Summary'); ?></th>
        </thead>
        <tbody>
            <?php foreach ($this->getCollection() as $_review): ?>
            <tr>
                <td data-label="<?php echo $this->__('Review Date'); ?>">
                    <span class="nobr"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></span>
                </td>
                <td data-label="<?php echo $this->__('Product Name'); ?>">
                    <h5 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a></h5>
                </td>
                <td data-label="<?php echo $this->__('Star Rating'); ?>">
                <?php if($_review->getSum()): ?>
                    <div class="reviews">
                        <div class="reviews__stars">
                            <div class="reviews__negative">
                                <?php for($i=0;$i<5;$i++) : ?>
                                    <?php echo Mage::helper('iweb_core/icons')->getSvg('general', 'star-full'); ?>
                                <?php endfor; ?>
                            </div>
                            <div class="reviews__positive" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;">
                                <?php for($i=0;$i<5;$i++) : ?>
                                    <?php echo Mage::helper('iweb_core/icons')->getSvg('general', 'star-full'); ?>
                                <?php endfor; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                </td>
                <td data-label="<?php echo $this->__('Review Summary'); ?>">
                    <p class="u-ellipsis"><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?></p>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-reviews-table')</script>
    <?php echo $this->getToolbarHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You have submitted no reviews.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
