<?php
/** @var $this Mage_Paypal_Block_Express_Review */
?>
<div class="page-title">
    <h1><?php echo $this->__('Review Order') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="alert alert--error js-shipping-alert u-hidden">
    <p><?php echo $this->__('Please select a shipping method before proceeding') ?></p>
</div>

<?php if ($this->getShippingAddress()): ?>
    <div class="info-set col2-set card--paypal-express-review">
        <div class="card__header">
            <h2 class="legend card__title"><?php echo $this->__('Shipping Information') ?></h2>
        </div>
        <div class="card__body">
            <div class="g-two-up g-gutter">
                <div class="col-1">
                    <div class="box">
                        <div class="box-title">
                            <h5><?php echo $this->__('Shipping Address') ?><span class="separator"><?php if ($this->getCanEditShippingAddress()):?> | </span><a href="<?php echo $this->getEditUrl() ?>"><?php echo $this->__('Edit') ?></a><?php endif;?></h5>
                        </div>
                        <div class="box-content">
                            <address><?php echo $this->renderAddress($this->getShippingAddress())?></address>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="box">
                        <div class="box-title">
                            <h5><?php echo $this->__('Shipping Method') ?></h5>
                        </div>
                        <div class="box-content">
                            <form method="post" id="shipping_method_form" action="<?php echo $this->escapeHtml($this->getShippingMethodSubmitUrl()) ?>">
                                <?php if ($this->getCanEditShippingMethod() || !$this->getCurrentShippingRate()):?>
                                    <?php if ($groups = $this->getShippingRateGroups()):?>
                                        <?php $currentRate = $this->getCurrentShippingRate(); ?>
                                        <fieldset>
                                            <select name="shipping_method" id="shipping_method" class="required-entry">
                                                <?php if (!$currentRate):?>
                                                    <option value=""><?php echo $this->__('Please select a shipping method...') ?></option>
                                                <?php endif;?>
                                                <?php foreach ($groups as $code => $rates):?>
                                                    <optgroup label="<?php echo $this->escapeHtml($this->getCarrierName($code)) ?>" style="font-style:normal;">
                                                        <?php foreach ($rates as $rate):?>
                                                            <option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
                                                                <?php echo $this->renderShippingRateOption($rate)?>
                                                            </option>
                                                        <?php endforeach;?>
                                                    </optgroup>
                                                <?php endforeach;?>
                                            </select>
                                        </fieldset>
                                        <p class="actions">
                                            <button id="update_shipping_method_submit" type="submit" class="button"><span><span><?php echo $this->__('Update Shipping Method') ?></span></span></button>
                                        </p>
                                    <?php else: ?>
                                        <p><strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong></p>
                                    <?php endif;?>
                                <?php else: ?>
                                    <p><strong><?php echo $this->renderShippingRateOption($this->getCurrentShippingRate())?></strong></p>
                                <?php endif; ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<div class="info-set col2-set card--paypal-express-review">
    <div class="card__header">
        <h2 class="legend card__title"><?php echo $this->__('Billing Information') ?></h2>
    </div>
    <div class="card__body">
        <div class="g-two-up g-gutter">
            <div class="col-1">
                <div class="box">
                    <div class="box-title u-offset-last">
                        <h5><?php echo $this->__('Payment Method') ?></h5>
                        <?php if($this->getEditUrl()):?><a href="<?php echo $this->getEditUrl() ?>" class="btn--edit-payment-info"><?php echo $this->__('Edit Payment Information') ?></a> <?php endif ?>
                    </div>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($this->getPaymentMethodTitle()) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="info-set card--paypal-express-review">
    <div class="card__header u-offset-last">
        <h2 class="legend card__title">
            <?php echo $this->__('Items in Your Shopping Cart') ?>
        </h2>
        <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="btn--edit-payment-info"><?php echo $this->__('Edit Shopping Cart') ?></a>
    </div>
    <div id="details-reload">
        <?php echo $this->getChildHtml('details') ?>
    </div>
</div>
<div class="alert alert--error js-shipping-alert u-hidden">
    <p><?php echo $this->__('Please select a shipping method before proceeding') ?></p>
</div>
<form method="post" id="order_review_form" action="<?php echo $this->getPlaceOrderUrl() ?>">
    <?php echo $this->getChildHtml('agreements'); ?>
    <div class="buttons-set buttons-set-order u-offset-last" id="review-buttons-container">
        <button type="button" id="review_button" value="<?php echo Mage::helper('core')->quoteEscape($this->__('Place Order')) ?>" class="button btn-checkout btn--paypal-express-review">
            <span><span><?php echo $this->__('Place Order') ?></span></span>
        </button>
        <button type="button" id="review_submit" value="<?php echo Mage::helper('core')->quoteEscape($this->__('Place Order')) ?>" class="button btn-checkout btn--paypal-express-review">
            <span><span><?php echo $this->__('Place Order') ?></span></span>
        </button>
        <span class="please-wait loading" id="review-please-wait" style="display:none;">
            <span class="loading__spinner"></span>
            <span class="loading__text"><?php echo $this->__('Submitting order information...') ?></span>
        </span>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    // submit buttons are not needed when submitting with ajax
    $('review_submit').hide();
    if ($('update_shipping_method_submit')) {
        $('update_shipping_method_submit').hide();
    }
    
    // iWeb Check if shipping method selected to show message
    var $j = jQuery;
    function checkShipping(){
        if($j('#shipping_method').val()){
            $j('.js-shipping-alert').addClass('u-hidden');
        }else{
            $j('.js-shipping-alert').removeClass('u-hidden');
        }
    }
    $j('#shipping_method').on('change', function(){
        checkShipping();
    });
    checkShipping();
    // end check shipping method
    
    <?php if ($this->getUseAjax()):?>
    OrderReviewController.prototype._submitOrder = function() {
        if (this._canSubmitOrder) {
            if (this._pleaseWait) {
                this._pleaseWait.show();
            }
            new Ajax.Request(this.form.action, {
                parameters: {isAjax: 1, method: 'POST'},
                onSuccess: function(transport) {
                    try{
                        response = eval('(' + transport.responseText + ')');
                    } catch (e) {
                        response = {};
                    }
                    if (response.redirect) {
                        setLocation(response.redirect);
                        return;
                    }
                    if (response.success) {
                        setLocation('<?php echo $this->getSuccessUrl()?>');
                        return;
                    } else {
                        var msg = response.error_messages;
                        if (typeof(msg)=='object') {
                            msg = msg.join("\n");
                        }
                        if (msg) {
                            $('review-please-wait').hide();
                            alert(msg);
                            return;
                        }
                    }
                    $('review-please-wait').hide();
                    alert('<?php echo $this->jsQuoteEscape($this->__('Unknown Error. Please try again later.')); ?>');
                    return;
                },
                onFailure: function(){
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                    $('review-please-wait').hide();
                }
            });
        }
    }
    <?php endif ?>

    PayPalExpressAjax = new OrderReviewController($('order_review_form'), $('review_button'),
        $('shipping_method'), $('shipping_method_form'), 'details-reload'
    );
    PayPalExpressAjax.addPleaseWait($('review-please-wait'));
    //]]>
</script>
