<?php
/**
 * @var $this Mage_Paypal_Block_Express_Shortcut
 */
?>
<span class="paypal-logo">
<?php $shortcutHtmlId = $this->getShortcutHtmlId() ?>
<?php $bmlShortcutHtmlId = $this->getBmlShortcutHtmlId() ?>
<?php if ($this->isOrPositionBefore()): ?>
    <span class="paypal-or break-or"><?php echo $this->__('-OR-'); ?></span>
<?php endif; ?>
<a data-action="checkout-form-submit" id="<?php echo $shortcutHtmlId ?>" href="<?php echo $this->getCheckoutUrl() ?>" class="btn--paypal">
    <img src="<?php echo $this->getImageUrl() ?>" alt="<?php echo Mage::helper('paypal')->__('Checkout with PayPal'); ?>" title="<?php echo Mage::helper('paypal')->__('Checkout with PayPal'); ?>" />
</a>
<?php if ($this->getIsBmlEnabled()): ?>
    <span class="paypal-or break-or"><?php echo $this->__('-OR-'); ?></span>
    </span>
<div class="bml-checkout-type">
    <span class="paypal-logo">
        <span class="bml_button">
            <a id="<?php echo $bmlShortcutHtmlId ?>" href="<?php echo $this->getBmlCheckoutUrl() ?>">
                <img src="<?php echo $this->getBmlImageUrl() ?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('paypal')->__('Checkout with PayPal Paypal Credit')); ?>" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('paypal')->__('Checkout with PayPal Paypal Credit')); ?>" class="btn--paypal" />
            </a>
            <a href="<?php echo $this->getMarketMessageUrl() ?>"><img src="<?php echo $this->getMarketMessage() ?>" /></a>
        </span>
    </span>
</div>
<?php else: ?>
    </span>
<?php endif; ?>
<?php if ($this->isOrPositionAfter()): ?>
<div>
    <span class="paypal-logo">
        <span class="paypal-or break-or"><?php echo $this->__('-OR-'); ?></span>
    </span>
</div>
 <?php endif; ?>
<?php if ($this->getConfirmationUrl() || $this->getIsInCatalogProduct()): ?>
<?php if ($this->getIsInCatalogProduct()): ?>
    <input type="hidden" id="pp_checkout_url" name="return_url" value="" />
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
    $$('#<?php echo $shortcutHtmlId ?>','#<?php echo $bmlShortcutHtmlId ?>').invoke('observe', 'click', function(event) {
        <?php if ($this->getConfirmationUrl()): ?>
            if (confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->getConfirmationMessage()) ?>')) {
                this.href = '<?php echo $this->getConfirmationUrl() ?>';
            }
        <?php endif; ?>
        <?php if ($this->getIsInCatalogProduct()): ?>
            $('pp_checkout_url').value = this.href;
            productAddToCartForm.submit(this);
            event.stop();
        <?php endif; ?>
    });
//]]>
</script>
<?php endif; ?>
