<?php
/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */

$html = '';

$children = $menuTree->getChildren();
$parentLevel = $menuTree->getLevel();
$childLevel = is_null($parentLevel) ? 0 : $parentLevel + 1;

$counter = 1;
$childrenCount = $children->count();

$parentPositionClass = $menuTree->getPositionClass();
$itemPositionClassPrefix = $parentPositionClass ? $parentPositionClass . '-' : 'nav-';

foreach ($children as $child) {
    $child->setLevel($childLevel);
    $child->setIsFirst($counter == 1);
    $child->setIsLast($counter == $childrenCount);
    $child->setPositionClass($itemPositionClassPrefix . $counter);

    $safe = strtolower(str_replace(array(' ','\'','&'), array('-','',''), $child->getName()));

    $outermostClassCode = 'level'. $childLevel;
    $_hasChildren = ($child->hasChildren()) ? 'has-children' : '';
    $linkAppend = Mage::helper('iweb_core/icons')->getSvg('custom--arrow-down');
    $linkToggleClass = '';
    $iconCheck = '';
    $dataAttr = sprintf('data-hover-toggle="nav-toggle-%s"', $safe);
    $linkToggleClass = '';

    $renderedItemAttr = $this->_getRenderedMenuItemAttributes($child);
    $renderedItemAttr = str_replace('class="', 'class="nav__item js-nav ', $renderedItemAttr);

    $html .= '<li '. $renderedItemAttr . $dataAttr . '>';

    $html .= '<a 
        href="'. $child->getUrl() .'" 
        class="'. $linkToggleClass .' '. $outermostClassCode .' '. $_hasChildren .'" ' .
        $dataAttr . '
    ><span>' . $this->escapeHtml($this->__($child->getName())) . '</span>' . $linkAppend . $iconCheck . '</a>';

    if (!empty($childrenWrapClass)) {
        $html .= '<div class="'. $childrenWrapClass .'">';
    }

    $nextChildLevel = $childLevel + 1;

    if (!empty($_hasChildren)) {
        $html .= '<ul class="nav level'. $childLevel .'" id="nav-' . $safe . '">';
        $html .=     '<li class="level'. $nextChildLevel .' view-all">';
        $html .=         '<a class="level'. $nextChildLevel .'" href="'. $child->getUrl() .'">';
        $html .=             $this->__('View All') . ' ' . $this->escapeHtml($this->__($child->getName()));
        $html .=         '</a>';
        $html .=     '</li>';
        $html .=     $this->render($child, $childrenWrapClass);
        $html .= '</ul>';
    }

    if (!empty($childrenWrapClass)) {
        $html .= '</div>';
    }

    $html .= '</li>';

    $counter++;
}

return $html;