<?php
$_product   = $this->getProduct();
$_helper    = $this->helper('catalog/output');
$_allowZoom = (bool)$this->getAllowZoom();
$_imgs       = $this->getGalleryArray();

?>

<div class="iweb-media-container">
	<div class="product-media-main product-image">
    	<ul class="product-image-gallery slider u-list-unstyled">
		  <?php $_i = 0; ?>
          <?php foreach($_imgs as $_img) : ?>
		  <?php $mainImg = $_img['mainImg']; ?>
		  
		  <?php // The data-slide-index needs to match the data slide indexes set in the thumbs ?>
		  <li data-slide-index="<?php echo $_i;?>">
			  <?php $_imgTag = '<img class="large" src="' . $mainImg . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
			  echo $_helper->productAttribute($_product, $_imgTag, 'image');
			  
			  $_i++
			  ?>
		  </li>
		  
		  <?php endforeach;?>
        </ul>
    </div>
</div>

<script>
(function($){
	var iwebMedia = new Iweb.Media({
	    allowZoom: <?php echo json_encode($_allowZoom); ?>,
		srcSetMode: false,
		zoomSpawnSelector: '.product-image-gallery.slider',
	    // Override the main media settings here
	    zoomSettings:{
	        // Override the zoom settings here        
	        media:{
	            // Override the iWeb media zoom settings here
	        }
	    }
	});

	// Example code of using the slider with BxSlider. Replace the following with
	// whichever slider's being used.
	$(document).ready(function(){
		var slider = $('.product-image-gallery.slider').bxSlider({
			'controls': false,
			'onSlideBefore': function($slideElement){
				iwebMedia.selectItemsByDataIndex($slideElement.data('slide-index'), false);
			},
		});
		
		$(iwebMedia).on('select-item', function(ev, data){
			slider.goToSlide(data.dataIndex);
		});
	});
}(jQuery));
</script>

<?php echo $this->getChildHtml('after'); ?>