<?php $_items = $this->getReviewsCollection()->getItems();?>
<?php if (count($_items)):?>
<div class="grid g-center">
    <div class="g-col-xl-8">

        <?php foreach ($_items as $_review):?>
            <div class="u-space-lg-bottom u-block-lg-bottom u-separator-bottom">
                <?php $_votes = $_review->getRatingVotes(); ?>
                <?php if (count($_votes)): ?>
                
                    <?php foreach ($_votes as $_vote): ?>
                    <div class="rating">
                        <div class="rating__stars rating-box">
                            <div class="rating__negative">
                                <?php for($i=0;$i<5;$i++) : ?>
                                    <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'star-full'); ?>
                                <?php endfor; ?>
                            </div>
                            <div class="rating__positive" style="width:<?php echo $_vote->getPercent() ?>%">
                                <?php for($i=0;$i<5;$i++) : ?>
                                    <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'star-full'); ?>
                                <?php endfor; ?>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                
                <?php endif; ?>
            
                <h5><?php echo $this->__('By %s', $this->escapeHtml($_review->getNickname())) ?> (<?php echo $this->__('%s', $this->formatDate($_review->getCreatedAt()), 'long') ?>)</h5>
            
                <p><?php echo nl2br($this->escapeHtml($_review->getDetail())) ?></p>
            </div>
        <?php endforeach; ?>
    
        <div class="grid g-collapse g-space g-center">
            <?php echo $this->getChildHtml('toolbar') ?>
        </div>
        
    </div>
</div>
<?php endif;?>