<div class="col2-set u-section-lg-bottom">
    <div class="box">
        <div>
            <h2 class="h3"><?php echo $this->__('Address Book') ?></h2>
        </div>
        <div class="box-content grid g-gutter g-stretch">
            <div class="g-col-md-6">
                <div class="col-1 bordered-box">
                    <div class="u-container u-section-xs">
                        <p class="lead"><?php echo $this->__('Default Billing Address') ?></p>
                        <address>
                            <p><?php echo $this->getPrimaryBillingAddressHtml() ?></p>
                            <p><a class="btn" href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a></p>
                        </address>
                    </div>
                </div>
            </div>
            <div class="g-col-md-6">
                <div class="col-2 bordered-box">
                    <div class="u-container u-section-xs">
                        <p class="lead"><?php echo $this->__('Default Shipping Address') ?></p>
                        <address>
                            <p><?php echo $this->getPrimaryShippingAddressHtml() ?></p>
                            <p><a class="btn" href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a></p>
                        </address>
                    </div>
                </div>
            </div>
        </div>
        <p class="u-section-xs-top"><a class="btn" href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a></p>
    </div>
</div>