<hr />
<h2 class="h3"><?php echo $this->__('Address Book') ?></h2>
<div class="box-content grid g-gutter g-stretch">
    <div class="g-col-md-6">
        
        <div class="box">
            <div class="box-title grid g-gutter g-baseline g-collapse">
                <div>
                    <h4><?php echo $this->__('Default Billing Address') ?></h4>
                </div>
                <div>
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </div>
            </div>
            <div class="box-content">
                <address>
                    <p><?php echo $this->getPrimaryBillingAddressHtml() ?></p>
                </address>
            </div>
        </div>
        
    </div>
    <div class="g-col-md-6">
        
        <div class="box">
            <div class="box-title grid g-gutter g-baseline g-collapse">
                <div>
                    <h4><?php echo $this->__('Default Shipping Address') ?></h4>
                </div>
                <div>
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </div>
            </div>
            <div class="box-content">
                <address>
                    <p><?php echo $this->getPrimaryShippingAddressHtml() ?></p>
                </address>
            </div>
        </div>
        
    </div>
</div>

<p><a class="btn btn--blue btn--sm" href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a></p>