<div class="col2-set grid g-gutter-x-lg">
    <div class="col-1 g-col-md-6">
        <div class="box">

            <div class="box-title grid g-gutter g-baseline g-collapse">
                <div>
                    <h4><?php echo $this->__('Contact Information') ?></h4>
                </div>
                <div>
                    <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
                </div>
            </div>
            <div class="box-content">
                <p>
                    <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br />
                    <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>
                </p>
                <p><a class="btn btn--blue btn--sm" href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a></p>
            </div>

        </div>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="col-2 g-col-md-6">
        <div class="box">
            <div class="box-title grid g-gutter g-baseline g-collapse">
                <div>
                    <h4><?php echo $this->__('Newsletters') ?></h4>
                </div>
                <div>
                    <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
                </div>
            </div>

            <div class="box-content">
                <p>
                    <?php if( $this->getIsSubscribed() ): ?>
                        <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                    <?php else: ?>
                        <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                    <?php endif; ?>
                </p>
            </div>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
    </div>
    <?php endif; ?>
</div>