<?php
/**
 * @see Mage_Paypal_Block_Express_Review_Details
 */
?>
<table id="details-table" class="data-table">
    <thead>
        <tr>
            <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
            <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            </tr>
        <?php endif; ?>
    </thead>
    <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach ?>
    </tbody>
</table>

<div class="grid">
    <div class="g-col-md-6"></div>
    <div class="g-col-md-6">
        <table class="data-table">
            <?php echo $this->getChildHtml('totals'); ?>
        </table>
    </div>
</div>
<script type="text/javascript">decorateTable('details-table');</script>
