<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
    
    <hgroup class="title title--actions">
        <div class="title__headings">
            <h1 class="title__title"><?php echo $this->__('Shopping Cart') ?></h1>
        </div>
        <?php if(!$this->hasError()): ?>
        <div class="title__actions">
            <div class="buttons-basket">
            <?php foreach ($this->getMethods('top_methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <?php echo $methodHtml; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        </div>
        <?php endif; ?>
    </hgroup>

    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>

        <table id="shopping-cart-table" class="data-table cart-table table--basket-items">
            <col />
            <col width="1" />
            <col width="1" />

        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
            <thead>
                <tr>
                    <th><?php echo $this->__('Product') ?></th>
                    <th><?php echo $this->__('Qty') ?></th>
                    <th><?php echo $this->__('Subtotal') ?></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="50" class="a-right">
                        
                        <span>
                            <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Clear Shopping Cart')); ?>" class="button btn-empty btn--basket-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                        </span>
                        
                        <button type="submit" name="update_cart_action"  value="update_qty" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Update Shopping Cart')); ?>" class="button btn-update btn--basket-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>

                        <?php if($this->getContinueShoppingUrl()): ?>
                            <span class="break-or">-or-</span>
                            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" class="button btn--basket-continue btn-continue" onclick="setLocation('<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>')">
                                <span><span><?php echo $this->__('Continue Shopping') ?></span></span>
                            </button>
                        <?php endif; ?>


                        
                        
                        <!--[if lt IE 8]>
                        <input type="hidden" id="update_cart_action_container" />
                        <script type="text/javascript">
                        //<![CDATA[
                            Event.observe(window, 'load', function()
                            {
                                // Internet Explorer (lt 8) does not support value attribute in button elements
                                $emptyCartButton = $('empty_cart_button');
                                $cartActionContainer = $('update_cart_action_container');
                                if ($emptyCartButton && $cartActionContainer) {
                                    Event.observe($emptyCartButton, 'click', function()
                                    {
                                        $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                        $cartActionContainer.setAttribute('name', 'update_cart_action');
                                        $cartActionContainer.setValue('empty_cart');
                                    });
                                }

                            });
                        //]]>
                        </script>
                        <![endif]-->
                    </td>
                </tr>
            </tfoot>
            <tbody>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('shopping-cart-table')</script>

    </form>
    
    <script type="text/javascript">
    (function($){
        var qtyWidget = new Iweb.QtyWidget({
            'delegateContainerSelector':'.js-qty'
        });
    }(jQuery));
    </script>
    
    <div class="cart-collaterals basket-additional">
        <div>
            <?php echo $this->getChildHtml('crosssell') ?>
            <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
        </div>
        <div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $this->getChildHtml('checkout.cart.extra') ?>
            <?php echo $this->getChildHtml('coupon') ?>
            
            <div class="totals">
                <?php echo $this->getChildHtml('totals'); ?>
                <?php if(!$this->hasError()): ?>
                <div class="buttons-basket">
                <?php foreach ($this->getMethods('methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <?php echo $methodHtml; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                </div>
                <?php endif; ?>
                
            </div>
        </div>
    </div>
    
</div>
