<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('build/js/opcheckout_rwd.js') ?>"></script>

<div class="u-section-sm">
    <ol class="opc u-list-unstyled" id="checkoutSteps">
    <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
    <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
        <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">

            <div class="step-title step-title--top" id="opc-step-<?php echo $_stepId ?>">
                <button class="btn btn--block">
                    <span class="tag tag--sm tag--badge">
                        <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'checkmark', 'icon--checkmark icon--sm'); ?>
                    </span>
                    <span class="number"><?php echo $i ?>.</span>
                    <span class="label"><?php echo $_stepInfo['label'] ?></span>
                </button>
            </div>
            <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item card" style="display:none;">
                <div class="card__header">
                    <h3 class="step-title"><?php echo $_stepInfo['label'] ?></h3>
                </div>
                <div class="card__body">
                    <?php echo $this->getChildHtml($_stepId) ?>
                </div>
            </div>
        </li>
    <?php endforeach ?>
    </ol>
</div>

<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>