<div class="u-container u-container--sm u-section">
    
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    
    <div class="page-title title u-text-center">
        <h1 class="title__main"><?php echo $this->__('Your order has been received.') ?></h1>
        <h2 class="sub-title title__sub"><?php echo $this->__('Thank you for your purchase!') ?></h2>
    </div>

    <?php echo $this->getChildHtml(); ?>
</div>