<hgroup class="title page-title">
    <h1 class="title__main"><?php echo $this->__('Your order has been received.') ?></h1>
    <h2 class="title__sub"><?php echo $this->__('Thank you for your purchase!') ?></h2>
</hgroup>
<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if ($this->getOrderId()):?>
    <div class="card--checkout-success">
        <div class="card__body">
            <?php echo $this->getChildHtml(); ?>
        </div>
        <div class="buttons-set card__footer">
            <button type="button" class="button btn--checkout-success" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" onclick="window.location='<?php echo $this->getUrl() ?>'">
                <span><span><?php echo $this->__('Continue Shopping') ?></span></span>
            </button>
        </div>
    </div>
 <?php endif;?>