<div class="page-sitemap card">
    <div class="page-title card__header">
        <h1 class="h2"><?php echo $this->getTitle() ?></h1>
    </div>
    <div class="card__body">
        <div id="sitemap_top_links">
            <?php echo $this->getChildHtml('links') ?>
        </div>
        
        <div class="grid g-center g-stretch-last g-reverse">
            <?php echo $this->getChildHtml('pager_top') ?>
        </div>
        <hr />
        
        <?php echo $this->getChildHtml('sitemap') ?>
        <?php echo $this->getChildHtml('links') ?>
        
        <hr />
        <div class="grid g-center g-stretch-last g-reverse">
            <?php echo $this->getChildHtml('pager_bottom') ?>
        </div>
        
    </div>
</div>
