<div class="card">
    <div class="card__header toggle-icon" data-cc-toggle-action="toggle" data-cc-toggle-target="#nav-customer" id="nav-customer-header">
        <h4><?php echo $this->getTitle(); ?></h4>
        <span class="toggle-icon__icon u-hidden-md u-hidden-lg u-hidden-xl"></span>
    </div>
    <div class="card__body u-toggle-xs u-toggle-sm" id="nav-customer" data-cc-toggle-target-callback="#nav-customer-title">
        <?php echo $this->getChildHtml(); ?>
    </div>
</div>