<div class="u-section-separator">
    <div class="bordered-box">
        <div class="u-clearfix u-fill-brand-lighter-blue">
            <div class="u-section-xs u-container">
                <h4>
                    <?php echo $this->getTitle(); ?>
                </h4>
                <div class="u-toggle-content u-toggle-content--md" id="nav-customer" data-cc-cascade="nav-customer-title">
                    <?php echo $this->getChildHtml(); ?>
                </div>
            </div>
        </div>
    </div>
</div>