<div id="modal-loading" class="modal modal--sm u-toggle" data-cc-cascade="loader">
    
    <div class="modal__dialog">
        
        <div class="card card--padded">
            <div class="card__body u-text-center">
                <span class="loading">
                    <span class="loading__spinner"></span>
                    <span class="loading__text">Please Wait</span>
                </span>
            </div>
        </div>
        
    </div>
    
</div>