<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */?>
<?php $_product = $this->getProduct() ?>

<?php echo $this->getPriceHtml($_product) ?>
<?php if ($this->displayProductStockStatus()): ?>
    <?php if (!$_product->isAvailable()): ?>
        <a href="#" class="btn btn--disabled btn--lg btn--block"><?php echo $this->__('Out of stock') ?></a>
    <?php endif; ?>
<?php endif; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>

