<div class="block block-account bordered-box">
    <div class="u-clearfix u-fill-brand-lighter-blue">
        <div class="u-section-xs u-container">
            <div class="block-title">
                <h4><span><?php echo $this->__('My Account'); ?></span></h4>
            </div>
            <div class="block-content">
                <ul class="nav nav--pills">
                    <?php $_links = $this->getLinks(); ?>
                    <?php $_index = 1; ?>
                    <?php $_count = count($_links); ?>
                    <?php foreach ($_links as $_link): ?>
                        <?php $_last = ($_index++ >= $_count); ?>
                        <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>