<div class="card--checkout-success-info">
    <div class="card__header">
        <h5 class="card__title"><?php echo $this->__('Your Order: %s', $this->escapeHtml($this->getOrderId())); ?></h5>
    </div>
    <div class="card__body">
    <?php if ($this->getOrderId()):?>
        <?php if ($this->getCanViewOrder()) :?>
            <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s" class="text-link">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
        <?php endif;?>
        
        <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>

    <?php endif;?>

    <?php if ($this->getAgreementRefId()): ?>
        <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
    <?php endif;?>

        <?php if ($profiles = $this->getRecurringProfiles()):?>
        <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
        <ul class="disc">
        <?php foreach($profiles as $profile):?>
            <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s" class="text-link">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
            <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
        <?php endforeach;?>
        </ul>
        <?php endif; ?>
    </div>
    <div class="card__footer">
        <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
            <span class="help-text">
                <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'" class="text-link">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
                <?php echo $this->getChildHtml() ?>
            </span>
        <?php endif;?>
    </div>
</div>