<div class="grid g-gutter-x-sm g-collapse">
    <div>
        <a href="<?php echo Mage::getUrl('customer/account'); ?>" class="u-visible-xs u-visible-sm btn">
            <span class="u-visually-hidden"><?php echo $this->__('My Account'); ?></span>
            <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'user'); ?>
        </a>
        <a href="<?php echo Mage::getUrl('customer/account'); ?>" class="u-hidden-xs u-hidden-sm btn btn--lg">
            <span class="u-visually-hidden"><?php echo $this->__('My Account'); ?></span>
            <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'user'); ?>
        </a>
    </div>
    <div>
        <?php echo $this->getChildHtml('summary') ?>
    </div>
</div>