<div class="u-visible-xs u-visible-sm u-block-bottom">
    <div class="grid g-stretch-first g-gutter-x-sm g-reverse">
        <div class="js-search-sm">
            <!-- search form -->
        </div>
        <div class="u-full-height">
            <a href="#" class="btn" data-cc-toggle-target="#drawer-nav" data-cc-toggle-action="activate">
                <span><?php echo $this->__('Browse'); ?></span>
                <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'menu'); ?>
            </a>
        </div>
    </div>
</div>