<nav class="u-separator">
    <ul class="nav nav--pills nav--branded nav--bordered nav--block">
        <li><a href="<?php echo $this->getUrl('') ?>"><?php echo Mage::helper('ydcore')->getSvgHtml('general--home'); ?> Homepage</a></li>
        <li><a href="<?php echo Mage::getUrl('customer/account'); ?>">My account</a></li>
        <li><a href="<?php echo $this->getUrl('delivery-information') ?>">Delivery information</a></li>
        <li><a href="<?php echo $this->getUrl('customer-services') ?>">Customer services</a></li>
        <li><a href="<?php echo $this->getUrl('our-services') ?>">Our services</a></li>
        <li><a href="<?php echo $this->getUrl('more-from-us') ?>">More from us</a></li>
        <li><a href="<?php echo Mage::getUrl('customer/account'); ?>">Sign in or Create an account</a></li>
    </ul>
</nav>