<div id="drawer-nav" data-cc-toggle-target-callback="#drawer-left" data-cc-toggle-group="drawer-left-tabs" class="u-toggle">
    <div class="u-block-lg">
        <div class="u-section-xs">
            <h2><?php echo $this->__('Browse'); ?></h2>
            <div class="u-section-xs-top u-section-sm-bottom js-primary-nav-sm"></div>
        </div>
    
        <a href="#" class="btn" data-cc-toggle-action="deactivate" data-cc-toggle-target="#drawer-left">Cancel</a>
    </div>
</div>