<div class="form-add">
    <h2 class="u-visually-hidden"><?php echo $this->__('Write Your Own Review') ?></h2>
    <?php if ($this->getAllowWriteReviewFlag()): ?>
        <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <fieldset>
                <?php echo $this->getChildHtml('form_fields_before')?>
                <h4><?php echo $this->__("You're reviewing:"); ?> <span><?php echo $this->escapeHtml($this->getProductInfo()->getName()) ?></span></h4>
                <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                    <?php foreach ($this->getRatings() as $_rating): ?>
                        <p class="h5">How do you rate this?</p>
                        <div class="rating rating--lg rating--input u-space-bottom">
                            <div class="rating__stars" id="product-ratings">
                                <?php foreach (array_reverse($_rating->getOptions()) as $_option): ?>
                                    <input type="radio" name="ratings[<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio">
                                    <label for="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>">
                                        <span class="u-visually-hidden"><?php echo $_option->getId() ?> star</span>
                                        <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'star-full'); ?>
                                    </label>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                <?php endif; ?>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field field-group">
                            <label for="nickname_field" class="field-group__label required"><?php echo $this->__('Name') ?> <em>*</em></label>
                            <div class="input-box field-group__field">
                                <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getNickname()) ?>" />
                            </div>
                        </div>
                        <div>
                            <label for="summary_field" class="required"><em>*</em><?php echo $this->__('Summary of Your Review') ?></label>
                            <div class="input-box">
                                <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" />
                            </div>
                        </div>
                        <div class="field field-group">
                            <label for="review_field" class="field-group__label required"><?php echo $this->__('Review') ?> <em>*</em></label>
                            <div class="input-box field-group__field">
                                <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry"><?php echo $this->escapeHtml($data->getDetail()) ?></textarea>
                            </div>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <div class="buttons-set">
                <button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="button"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
            </div>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var dataForm = new VarienForm('review-form');
            Validation.addAllThese(
                [
                    ['validate-rating', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Please select one of each of the ratings above')) ?>', function(v) {
                        var inputs = $('product-ratings').select('input');
                        var error = 1;

                        for( var j=0; j < inputs.length; j++ ) {
                            if( j > 0 ) {
                                for( i in inputs ) {
                                    if(inputs[i].checked) {
                                        error = 0;
                                    }
                                }

                                if( error == 1 ) {
                                    return false;
                                } else {
                                    error = 1;
                                }
                            }
                        }
                        return true;
                    }]
                ]
            );
            //]]>
        </script>
    <?php else: ?>
        <p class="review-nologged" id="review-form">
            <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
        </p>
    <?php endif ?>
</div>
