<?php
$_sku = $this->getProductSku();
$_invert = $this->getInvert();
if($_sku) :
?>
    <?php 
        $_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $_sku);
        $_helper = $this->helper('catalog/output');
    ?>
    <?php if($_product) : ?>
        <div class="featured-product featured-product--hero <?php if($_invert) { echo 'u-fill-brand-light-blue'; } ?>">
            <div class="u-section-lg">
                <div class="featured-product__header">
                    <hgroup class="title title--bordered title--strikethrough <?php if($_invert) { echo 'title--invert'; } ?>">
                        <h2 class="title__main"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></h2>
                        <h5 class="title__sub"><?php echo $this->__('bundle'); ?></h5>
                    </hgroup>
                    <p <?php if($_invert) { echo ' class="u-text-white"'; } ?>><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
                </div>
                <div class="featured-product__img">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image card__body">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(600) ?>" width="600" height="600" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" class="u-img-responsive" />
                    </a>
                </div>
                <div class="featured-product__footer <?php if($_invert) { echo 'u-text-white'; } ?>">
                    <p todo>PRICE</p>
                    <?php //echo $this->getPriceHtml($_product); ?>
                    <p><a href="<?php echo $_product->getProductUrl() ?>" class="btn btn--grey btn--arrow">Shop Now</a></p>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>