<?php $_products = $this->getProductCollection(); ?>
<?php $_imgWidth = $this->getImageWidth(); ?>
<?php $_imgHeight = $this->getImageHeight(); ?>
<?php $_heading = $this->getHeading(); ?>
<?php $_blockHelper = $this->helper('iweb_core/block'); ?>
<?php $_helper = $this->helper('catalog/output'); ?>

<?php if(!count($_products)): return; endif; ?>
    

<div class="grid g-stretch">
    <?php foreach ($_products as $_product): ?>
        <div class="g-col-xs-6 g-col-md-3">
            <div class="featured-product">
                <div class="u-section-lg">
                    <div class="featured-product__img">
                        <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->escapeHtml($_product->getName()); ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($_imgWidth, $_imgHeight); ?>" alt ="<?php echo $this->escapeHtml($_product->getName()); ?>" />
                        </a>
                    </div>
                    <div class="featured-product__body">
                        <span class="tag u-hidden-xs" todo><?php echo $this->__('Best Seller'); ?></span>
                        <h4>
                            <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->escapeHtml($_product->getName()); ?>">
                                <?php echo $this->escapeHtml($_product->getName()); ?>
                            </a>
                        </h4>
                        <p class="u-hidden-xs u-hidden-md"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
                    </div>
                    <div class="featured-product__footer">
                        <?php echo $this->getPriceHtml($_product); ?>
                        <p><a href="<?php echo $_product->getProductUrl(); ?>" class="btn btn--grey btn--arrow">Shop Now</a></p>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>