<div class="hero-banner js-responsive-background" data-image="<?php echo $this->getSkinUrl('/build/img/hero-banner.jpg'); ?>" data-image-lg="<?php echo $this->getSkinUrl('/build/img/hero-banner-lg.jpg'); ?>">
    <div class="u-container">
        <div class="title title--center title--invert">
            <h4 class="title__sub">Total Nutrition</h4>
            <h1 class="title__main">Join the Tonu Revolution</h1>
            <p class="title__tagline">Tonu meal replacement and supplements.</p>
        </div>
        <p><a href="<?php echo $this->getUrl(''); ?>our-products.html" class="btn btn--arrow btn--invert">Shop Now</a> &nbsp;&nbsp;<a href="#" class="btn btn--arrow btn--invert">Why Us?</a>
    </div>
    <div class="hero-banner__footer">
        <ul class="trust-logos trust-logos--lg">
            <li><a href="#"><img src="<?php echo $this->getSkinUrl('build/img/informed-choice-invert.png'); ?>" alt="Informed Choice" /></a></li>
            <li><a href="#"><img src="<?php echo $this->getSkinUrl('build/img/informed-sport-invert.png'); ?>" alt="Informed Sport" /></a></li>
        </ul>
    </div>
</div>