<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_modifierClass = "";
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
    if($_imgUrl) {
        $_modifierClass = " o-category-masthead--split";
    }
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="o-category-masthead<?php echo $_modifierClass; ?>">
    <?php if($_imgUrl) : ?>
    <div class="o-category-masthead__aside">
        <?php if($_imgUrl): ?>
            <?php echo $_imgHtml ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="o-category-masthead__body">
        <hgroup class="title title--actions">
            <h1 class="u-text-blue"><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
            <div class="title__actions u-visible-xs">
                <a href="#" class="btn btn--info" data-cc-target="drawer-left-facets" data-cc-action="activate"><?php echo $this->__('Refine'); ?></a>
            </div>
        </hgroup>
        <?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
            <div class="category-description std">
                <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>