<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
?>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="hero-banner hero-banner--sm js-responsive-background" data-image="<?php echo $this->getSkinUrl('/build/img/hero-banner.jpg'); ?>" data-image-lg="<?php echo $this->getSkinUrl('/build/img/hero-banner-lg.jpg'); ?>">
    <div class="u-container">
        <div class="title title--center title--invert">
            <h1 class="title__main"><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
        </div>
    </div>
</div>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
