<div class="u-container u-container--sm u-section-sm-top u-section-lg-bottom u-text-center">
    <div class="page-title">
        <h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
    </div>
    <div class="cart-empty">
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
        <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
        <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl())) ?></p>
        <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
    </div>
</div>