<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */

?>
<?php if ($this->getIsNeedToDisplaySideBar()):?>
    
    <?php
    $_cartQty = $this->getSummaryCount();

    $_items = "";
    $_total = Mage::helper('checkout')->formatPrice($this->getSubtotal());
    if ($_cartQty == 1): 
        $_items = $this->__('(1)');
    else :
        $_items = $this->__('(%d)', $_cartQty);
    endif;
    ?>

    <div class="header__btn header__btn--last">
        <a href="<?php echo $this->getUrl('checkout/cart'); ?>">
            <span class="u-visually-hidden"><?php echo $this->__('My Cart'); ?></span>
            <?php echo Mage::helper('chopchop/icon')->getSvgHtml('custom', 'basket'); ?>
        </a>
    </div>


<?php endif;?>




