<div class="header__list">
    <a href="<?php echo $this->getUrl('wishlist'); ?>" class="btn btn--blue btn--my-list">
        <span class="icon-my-list">
            <img src="<?php echo $this->getSkinUrl('build/img/icons/pf/list.svg'); ?>" alt="<?php echo $this->__('My Wishlist'); ?>" width="24" height="40">
        </span>
        <span class="opt"><?php echo $this->__('My Wishlist'); ?></span>
    </a>
</div>