<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<div class="grid g-gutter">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="g-col-md-6">
        

            <div>
            <hgroup class="title">
                <h4><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h4>
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                    <p><?php echo $this->__('Register with us for future convenience') ?></p>
                <?php endif; ?>
            </hgroup>
            <div class="u-section-xs">
                <?php if(!$this->getQuote()->isAllowedGuestCheckout() ): ?>
                    <p><strong><?php echo $this->__('Register and save time!') ?></strong></p>
                    <ul class="u-list-unstyled">
                        <li><?php echo $this->__('Fast and easy check out') ?></li>
                        <li><?php echo $this->__('Easy access to your order history and status') ?></li>
                    </ul>
                <?php endif; ?>
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                    <ul class="form-list u-list-unstyled">
                        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                        <li class="control">
                            <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                        </li>
                        <?php endif; ?>
                    
                        <li class="control">
                            <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
                        </li>
                    </ul>

                        <h4 class="u-hidden"><?php echo $this->__('Register and save time!') ?></h4>
                        <ul class="ul u-hidden">
                            <li><?php echo $this->__('Fast and easy check out') ?></li>
                            <li><?php echo $this->__('Easy access to your order history and status') ?></li>
                        </ul>

                <?php else: ?>
                    <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
                <?php endif; ?>
            </div>
        </div>
        
        <div class="buttons-set">
            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="button btn btn--red" onclick="checkout.setMethod();">
                    <span><span><?php echo $this->__('Continue') ?></span></span>
                </button>
            <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
                <button id="onepage-guest-register-button" type="button" class="button btn btn--red" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'">
                    <span><span><?php echo $this->__('Register') ?></span></span>
                </button>
            <?php else: ?>
                <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="button btn btn--red">
                        <span><span><?php echo $this->__('Register') ?></span></span>
                    </button>
                </form>
            <?php endif; ?>
        </div>

        
    </div>
    
    
    <div class="g-col-md-6">
        <hr class="u-visible-xs u-visible-sm" />

            <hgroup class="title">
                <h4 class="title__main"><?php echo $this->__('Returning Customers') ?></h4>
                <p class="title__sub"><?php echo $this->__('Sign in to speed up your checkout process') ?></p>
            </hgroup>
            <?php echo $this->getMessagesBlock()->toHtml() ?>
            <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" class="u-section-xs">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <ul class="form-list u-list-unstyled">
                    <li class="field-group">
                        <label for="login-email" class="field-group__label required"><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                        </div>
                    </li>
                    <li class="field-group">
                        <label for="login-password" class="field-group__label required"><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <input name="context" type="hidden" value="checkout" />
            </form>

        
        <div class="buttons-set grid g-stretch-first">
            <div>
                <p class="micro required u-hidden"><?php echo $this->__('* Required Fields') ?></p>
                <button type="submit" class="button btn btn--red" onclick="onepageLogin(this)">
                    <span><span><?php echo $this->__('Login') ?></span></span>
                </button>
            </div>
            <div class="u-text-right">
                <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="micro"><?php echo $this->__('Forgot your password?') ?></a>
            </div>
        </div>
        
    </div>

</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
