<div class="grid g-center">
    <div class="g-col-xl-8">
        
        <div class="form-add">
            
            <?php if ($this->getAllowWriteReviewFlag()): ?>
            <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <?php echo $this->getChildHtml('form_fields_before')?>
                
                <div class="grid g-stretch-last g-gutter-x">
                    <div>
                        <img src="product-img.jpg" alt="Product Img" />
                    </div>
                    <div class="g-col-sm-10">
                        <div class="title">
                            <h4><?php echo $this->__('You are reviewing'); ?></h4>
                            <h5><?php echo $this->escapeHtml($this->getProductInfo()->getName()) ?></h5>
                        </div>
                    </div>
                </div>
                
                <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                <hr />
                <h5><?php echo $this->__('How do you rate this product?') ?></h5>
                <div class="rating rating--lg rating--input">
                    <span id="input-message-box"></span>
                    <?php foreach ($this->getRatings() as $_rating): ?>
                        <div class="rating__stars">
                            <span class="u-visually-hidden"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></span>
                            <?php foreach ($_rating->getOptions() as $_option): ?>
                                <input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio" />
                                <label for="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>">
                                    <span class="u-visually-hidden"><?php echo $this->__('%s stars', $_option->getId()); ?></span>
                                    <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'star-full'); ?>
                                </label>
                            <?php endforeach; ?>
                        </div>
                    <?php endforeach; ?>
                    
                    <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                </div>
                <hr />
                <?php endif; ?>
                    <fieldset class="u-clearfix grid">
                        <ul class="form-list g-col-sm-10 g-col-lg-8">
                            <li class="field-group">
                                <label for="nickname_field" class="required"><em>*</em><?php echo $this->__('Nickname') ?></label>
                                <div class="input-box">
                                    <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getNickname()) ?>" />
                                </div>
                            </li>
                            <li class="field-group">
                                <label for="summary_field" class="required"><em>*</em><?php echo $this->__('Summary of Your Review') ?></label>
                                <div class="input-box">
                                    <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" />
                                </div>
                            </li>
                            <li class="field-group">
                                <label for="review_field" class="required"><em>*</em><?php echo $this->__('Review') ?></label>
                                <div class="input-box">
                                    <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry"><?php echo $this->escapeHtml($data->getDetail()) ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="buttons-set">
                        <button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="button"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
                    </div>
            </form>
            <script type="text/javascript">
            //<![CDATA[
                var dataForm = new VarienForm('review-form');
                Validation.addAllThese(
                [
                    ['validate-rating', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Please select one of each of the ratings above')) ?>', function(v) {
                            var trs = $('product-review-table').select('tr');
                            var inputs;
                            var error = 1;

                            for( var j=0; j < trs.length; j++ ) {
                                var tr = trs[j];
                                if( j > 0 ) {
                                    inputs = tr.select('input');

                                    for( i in inputs ) {
                                        if( inputs[i].checked == true ) {
                                            error = 0;
                                        }
                                    }

                                    if( error == 1 ) {
                                        return false;
                                    } else {
                                        error = 1;
                                    }
                                }
                            }
                            return true;
                        }]
                ]
                );
            //]]>
            </script>
            <?php else: ?>
            <p class="review-nologged" id="review-form">
                <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
            </p>
            <?php endif ?>
        </div>

    </div>
</div>