<div class="grid g-stretch g-collapse">
    <div>
        <p class="h4"><?php echo $this->getTitle(); ?></p>
    </div>
    <div>
        <a href="#" class="btn btn--sm" data-cc-action="deactivate" data-cc-target="modal"><?php echo $this->__('Close'); ?></a>
    </div>
</div>

<div class="card">
    <div class="card__body">
        <div class="<?php echo $this->getJsPlaceHolderClass(); ?>"></div>
        <?php echo $this->getChildHtml(); ?>
    </div>
</div>