<div class="page-title">
    <h1><?php echo Mage::helper('customer')->__('You are now logged out') ?></h1>
</div>
<div>
    <p><?php echo Mage::helper('customer')->__('You have logged out and will be redirected to our homepage in 5 seconds.') ?></p>
</div>

<script type="text/javascript">
//<![CDATA[
    setTimeout(function(){ location.href = '<?php echo $this->getUrl() ?>'},5000);
//]]>
</script>
