<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail" class="single-form single-form--invert">
    <div class="field-group input-box">
        <input type="text" name="email" id="newsletter" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="u-fill-white">
    </div>
    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="btn btn--text">
        <?php echo Mage::helper('iweb_core/icons')->getSvg('custom--arrow-right'); ?>
    </button>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</form>
