<div class="block block-progress opc-block-progress">
    <div class="block-title card__header u-hidden">
        <h6 class="card__title"><?php echo $this->__('Your Checkout Progress') ?></h6>
    </div>
    <div class="block-content">
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
        <div id="billing-progress-opcheckout">
            <?php echo $this->getChildHtml('billing.progress') ?>
        </div>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
        <div id="shipping-progress-opcheckout">
            <?php echo $this->getChildHtml('shipping.progress') ?>
        </div>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
        <div id="shipping_method-progress-opcheckout">
            <?php echo $this->getChildHtml('shippingmethod.progress') ?>
        </div>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <div id="payment-progress-opcheckout">
            <?php echo $this->getChildHtml('payment.progress') ?>
        </div>
        <?php endif; ?>
    </div>
</div>

