<div>
    <form action="" id="co-shipping-form">
        <ul class="form-list u-list-unstyled g-col-md-9">
        <?php if ($this->customerHasAddresses()): ?>
           <li class="wide field-group">
               <label for="shipping-address-select" class="field-group__label"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
               <div class="input-box field-group__field">
                   <?php echo $this->getAddressesHtmlSelect('shipping') ?>
               </div>
           </li>
        <?php endif ?>
            <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
                <div>
                    <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                    <ul class="u-list-unstyled">
                        <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?></li>
                        <li class="fields">
                            <div class="fields field-group">
                                <label for="shipping:company" class="field-group__label"><?php echo $this->__('Company') ?></label>
                                <div class="input-box field-group__field">
                                    <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field field-group">
                                <label for="shipping:telephone" class="field-group__label required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                                <div class="input-box field-group__field">
                                    <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                                    <p class="micro"><?php echo $this->__('(We may need to contact you if there is a problem with your delivery.)'); ?></p>
                                </div>
                            </div>
                        </li>
                        <li class="wide field-group">
                                <label for="shipping:postcode" class="field-group__label required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                <div class="input-box field-group__field">
                                    <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="g-col-xs-5 input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                        </li>

                    </ul>
                    <ul class="u-list-unstyled">
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="wide field-group">
                            <label for="shipping:street1" class="field-group__label required"><em>*</em><?php echo $this->__('Address') ?></label>
                            <div class="input-box field-group__field">
                                <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </li>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="wide field-group">
                            <div class="input-box field-group__field">
                                <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </li>
                <?php endfor; ?>
                        <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="wide field-group">
                            <label for="billing:vat_id" class="field-group__label"><?php echo $this->__('VAT Number'); ?></label>
                            <div class="input-box field-group__field">
                                <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                            </div>
                        </li>
                        <?php endif; ?>
                        <li class="fields">
                            <div class="field field-group">
                                <label for="shipping:city" class="field-group__field required"><em>*</em><?php echo $this->__('City') ?></label>
                                <div class="input-box field-group__label">
                                    <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                            <div class="field field-group">
                                <label for="shipping:region" class="field-group__label required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                <div class="input-box field-group__field">
                                    <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                    </select>
                                    <script type="text/javascript">
                                    //<![CDATA[
                                        $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                    //]]>
                                    </script>
                                    <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field field-group u-hidden">
                                <label for="shipping:country_id" class="field-group__label required"><em>*</em><?php echo $this->__('Country') ?></label>
                                <div class="input-box field-group__field">
                                    <?php echo $this->getCountryHtmlSelect('shipping') ?>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <ul class="u-list-unstyled">
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control field-group">
                            <label for="shipping:save_in_address_book">
                                <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save in address book')) ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                                <?php echo $this->__('Save in address book') ?>
                            </label>
                        </li>
                    <?php else:?>
                        <li class="no-display u-hidden"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                    <?php endif;?>
                    </ul>
                </div>
            </li>
            <li class="control field-group">
                <label for="shipping:same_as_billing">
                    <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" />
                    <?php echo $this->__('Use Billing Address') ?>
                </label>
            </li>
        </ul>
        <hr />
        <div class="buttons-set grid g-stretch-last g-center g-gutter-x" id="shipping-buttons-container">
            <div>
                <p class="required u-visually-hidden"><?php echo $this->__('* Required Fields') ?></p>
                <a href="#opc-shipping" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue')) ?>" class="button btn-continue btn--block" onclick="shipping.save()">
                    <span><span><?php echo $this->__('Continue') ?></span></span>
                </a>
            </div>
            <div>
                <span class="loading" id="shipping-please-wait" style="display:none;">
                    <span class="u-shape-ring u-spin"></span>
                    <span class="loading__text"><?php echo $this->__('Loading next step...') ?></span>
                </span>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Select State/Province...')) ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>
