<hgroup class="title title--actions">
    <div class="title__headings page-title">
        <h1 class="title__main"><?php echo $this->__('Secure Checkout') ?></h1>
        <h3 class="title__sub"><?php echo $this->__('Enter Your Details Below'); ?></h3>
    </div>
    <div class="title__actions">
        <small><?php echo $this->__('Forgot an Item?'); ?></small>
        <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="btn btn--sm btn--edit-basket"><?php echo $this->__('Edit Your Basket'); ?></a>
    </div>
</hgroup>