<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>


    
    <div class="g-col-sm-7 g-col-md-6 g-col-lg-5 g-col-xl-6">
    
        <div class="grid g-stretch-last">
            <div>
                <?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"><?php endif;?><img src="<?php echo $this->getProductThumbnail()->resize(65); ?>" width="65" height="65" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /><?php if ($this->hasProductUrl()):?></a><?php endif;?>
            </div>
            <div>
                <h5 class="product-name">
                <?php if ($this->hasProductUrl()):?>
                    <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $this->escapeHtml($this->getProductName()) ?>
                <?php endif; ?>
                </h5>
            
            
                    <?php if ($canApplyMsrp): ?>
                        <span class="cart-price">
                            <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                            <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
                            <script type="text/javascript">
                                Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
                            </script>
                        </span>
                <?php else: ?>

                        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <?php else: ?>
                                <span class="cart-price">
                            <?php endif; ?>
        
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                                <?php else: ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                                <?php endif; ?>

                            </span>

                            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                                <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                        <?php endforeach; ?>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                        <?php endforeach; ?>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                        <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                                    </div>
                                <?php endif; ?>
            
                            <?php endif; ?>
        
                        <?php endif; ?>
    
                        <?php if ($_options = $this->getOptionList()):?>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <div class="truncated_full_value">
                                    <dl class="item-options">
                                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                    </dl>
                                </div>
                                <?php endif; ?>
                            </dd>
                            <?php endforeach; ?>
                        </dl>
                        <?php endif;?>
    
                        <?php if ($messages = $this->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
                        <?php endforeach; ?>
                        <?php endif; ?>
                        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
    
                        <?php if ($addInfoBlock): ?>
                            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                        <?php endif;?>
                    <?php endif;?>
                
            </div>
        </div>
    
    </div>

    <div class="g-col-sm-5 g-col-md-6 g-col-lg-7 g-col-xl-6">
        
        

                <label for="cart[<?php echo $_item->getId() ?>][qty]"><?php echo $this->__('Qty:'); ?></label>

        <div class="grid g-center g-gutter-x">
            <div class="g-col-xs-4">
                <input type="number" name="cart[<?php echo $_item->getId() ?>][qty]" data-cart-item-id="<?php echo $this->jsQuoteEscape($_item->getSku()) ?>" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text u-text-center qty" maxlength="12" />
            </div>
            <div class="g-col-xs-8">
                
                <div>
                    <button type="submit" name="update_cart_action" data-cart-item-update value="update_qty" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Update')); ?>" class="button btn--sm btn--text btn-update js-update-qty" disabled>
                        <span><span><?php echo $this->__('Update'); ?></span></span>
                    </button>
                    <a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove item')) ?>" class="btn-remove btn-remove2 btn btn--text btn--sm"><?php echo $this->__('Remove item')?></a>
                </div>
                
            </div>
        </div>

    
        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
            <?php if ($isVisibleProduct): ?>
                <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="link-wishlist use-ajax"><?php echo $this->__('Move'); ?></a>
            <?php endif ?>
        <?php endif ?>
    
    </div>