<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<div class="card o-facet o-facet--blocky currently">
    <div class="card__header">
        <h4><?php echo $this->__('Currently Shopping by:') ?></h4>
    </div>
    <div class="card__body">
        <ol class="nav nav--pills">
            <?php foreach ($_filters as $_filter): ?>
            <li>
                <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    if ($clearLinkUrl):
                ?>
                <a class="btn-remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>">
                    <?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>
                </a>
                <?php else: ?>
                <a class="btn-remove" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>">
                    <i class="icon-cancel"></i><span class="u-visually-hidden"><?php echo $this->__('Remove This Item') ?></span>
                    <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span>
                    <span class="value"><?php echo $this->stripTags($_filter->getLabel()) ?></span>
                </a>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    
    <?php if ($this->getLayer()->getState()->getFilters()): ?>
    <div class="actions card__footer">
        <a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>