<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav js-move-filters">
    <div class="block-title u-hidden">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if($this->canShowOptions()): ?>
        <div id="narrow-by-list">
            <?php $_filters = $this->getFilters() ?>
            <?php foreach ($_filters as $_filter): ?>
                <div class="card o-facet">
                <?php if($_filter->getItemsCount()): ?>
                    <?php $cleanName = strtolower(str_replace(" ","-",$_filter->getName())); ?>
                    <div class="card__header expand-toggle" data-cc-action="toggle" data-cc-target="filter-<?php echo $cleanName; ?>" id="filter-title-<?php echo $cleanName; ?>">
                        <h4 class="card__title"><?php echo $this->__($_filter->getName()) ?></h4>
                        <span class="shape"></span>
                    </div>
                    <div class="card__body u-toggle" id="filter-<?php echo $cleanName; ?>" data-cc-cascade="filter-title-<?php echo $cleanName; ?>">
                        <?php echo $_filter->getHtml() ?>
                    </div>
                <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>