<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <?php if( $this->isExpanded() ): ?>
        
        <?php if( $this->isEnabledViewSwitcher() ): ?>
        <div class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <label class="view-mode__label u-visually-hidden"><?php echo $this->__('View as') ?>:</label>
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <a href="#" title="<?php echo $_label ?>" class="is-active <?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
                <?php else: ?>
                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        
        <div class="sorter">
            <label class="u-visually-hidden"><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
                <optgroup label="<?php echo $this->__('Sort By') ?>">
                <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                    <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__($_order) ?>
                    </option>
                <?php endforeach; ?>
                </optgroup>
            </select>
            <span class="sorter__direction">
                <?php if($this->getCurrentDirection() == 'desc'): ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?>" class="sorter__asc">
                        <span class="shape"></span>
                    </a>
                <?php else: ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?>" class="sorter__desc">
                        <span class="shape"></span>
                    </a>
                <?php endif; ?>
            </span>
        </div>
    <?php endif; ?>
    
    <div class="amount u-visually-hidden">
        <?php if($this->getLastPageNum()>1): ?>
            <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
        <?php else: ?>
            <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </div>

    <div class="limiter">
        <label class="u-visually-hidden"><?php echo $this->__('Show') ?></label>
        <select onchange="setLocation(this.value)">
            <optgroup label="<?php echo $this->__('Number per page') ?>">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </optgroup>
        </select>
        <span class="u-visually-hidden"><?php echo $this->__('per page') ?></span>
    </div>

    <?php echo $this->getPagerHtml() ?>

<?php endif ?>
