<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="has-amount-sorter">
    <div class="grid g-collapse g-space u-space-lg-bottom">
        <div class="amount">
            <?php if($this->getLastPageNum()>1): ?>
                <strong><?php echo $this->__('Showing %s of %s results', $this->getLastNum(), $this->getTotalNum()) ?></strong>
            <?php else: ?>
                <strong><?php echo $this->__('Showing all %s results', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </div>
    
        <div>
            <?php if( $this->isExpanded() ): ?>
            <div class="sorter">
                <?php if( $this->isEnabledViewSwitcher() ): ?>
                <p class="view-mode u-hidden">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                    <label><?php echo $this->__('View as') ?>:</label>
                    <?php foreach ($this->getModes() as $_code=>$_label): ?>
                        <?php if($this->isModeActive($_code)): ?>
                            <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
                        <?php else: ?>
                            <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </p>
                <?php endif; ?>

                <div class="sort-by grid g-gutter-x g-collapse">
                    <div>
                        <label><?php echo $this->__('Sort By') ?></label>
                    </div>
                    <div class="grid g-gutter-x g-center g-stretch-last">
                        <div>
                            <select onchange="setLocation(this.value)">
                            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $this->__($_order) ?>
                                </option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                        <div>
                        <?php if($this->getCurrentDirection() == 'desc'): ?>
                            <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?>">
                                <span class="u-visually-hidden"><?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?></span>
                                <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'arrow-up6'); ?>
                            </a>
                        <?php else: ?>
                            <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?>">
                                <span class="u-visually-hidden"><?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?></span>
                                <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'arrow-down6'); ?>
                            </a>
                        <?php endif; ?>
                        </div>
                    </div>
                </div>
                
            </div>
            <?php endif; ?>
        
        </div>
    </div>
</div>

<div class="u-space-sm-top has-pager-limiter">
    <div class="grid g-collapse g-space g-center">
        <div class="pager">
            <?php echo $this->getPagerHtml() ?>
        </div>
        
        <div class="limiter grid g-gutter-x-sm g-collapse">
            <div>
                <label><?php echo $this->__('Show') ?></label>
            </div>
            <div>
                <select onchange="setLocation(this.value)">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div>
            <div class="u-hidden-xs">
                <label><?php echo $this->__('per page') ?></label>
            </div>
        </div>
    </div>
</div>
<?php endif ?>