<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="card--forgot-password">
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <div class="card__header">
            <h2 class="legend card__title"><?php echo $this->__('Retrieve your password here') ?></h2>
        </div>
        <div class="card__body">
            <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
            <ul class="form-list">
                <li class="field">
                    <label for="email_address" class="required"><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>

        <div class="buttons-set card__footer">
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button btn--forgot-password-submit"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            <span class="help-text required"><?php echo $this->__('* Required Fields') ?></span>
        </div>
    </form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
