<div class="page-title">
    <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<div class="card--customer-newsletter">
    <form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="card__header">
                <h2 class="legend card__title"><?php echo $this->__('Email Newsletters') ?></h2>
            </div>
            <div class="card__body">
                <ul class="form-list">
                    <li class="control field-group field-group--inline">
                        <div class="field-group__field">
                            <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('General Subscription')) ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        </div>
                        <div class="field-group__label">
                            <label for="subscription"><?php echo $this->__('General Subscription') ?></label>
                        </div>
                    </li>
                    
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
                </ul>
            </div>
        </div>
        <div class="buttons-set card__footer">
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button btn--customer-newsletter"><span><span><?php echo $this->__('Save') ?></span></span></button>
        </div>
    </form>
</div>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
