<div class="page-title">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate">
    <div class="fieldset card">
        <div class="card__body">
            <ul class="form-list">
                <li class="field-group">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                    </div>
                </li>
                <li class="field-group">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="card__footer">
            <div class="buttons-set">
                <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>" class="button btn--red"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
