<?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
<div class="card--checkout-progress">
    <div class="card__header complete">
        <h6 class="card__title"><?php echo $this->__('Billing Address') ?></h6>
        <a href="#billing" class="btn--checkout-change" onclick="checkout.changeSection('opc-billing'); return false;"><?php echo $this->__('Change') ?></a>
    </div>
    <div class="card__body complete">
        <address><?php echo $this->getBilling()->format('html') ?></address>
    </div>
</div>
<?php endif; ?>