<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<div class="card--checkout-progress">
    <div class="card__header complete">
        <h6 class="card__title"><?php echo $this->__('Payment Method') ?></h6>
        <a href="#payment" class="btn--checkout-change" onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Change') ?></a>
    </div>
    <div class="card__body complete">
        <?php echo $this->getPaymentHtml() ?>
    </div>
</div>
<?php endif; ?>