<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
<?php $completeClass = $this->getCheckout()->getStepData('shipping', 'complete') ? 'complete' : ''; ?>
<div class="card--checkout-progress">
    <div class="card__header <?php echo $completeClass ?>">
        <h6 class="card__title"><?php echo $this->__('Shipping Address') ?></h6>
        <a href="#payment" class="btn--checkout-change" onclick="checkout.changeSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a>
    </div>
    <div class="card__body <?php echo $completeClass ?>">
        <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
        <address><?php echo $this->getShipping()->format('html') ?></address>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>