<div class="u-container-lg u-section-sm">
    <div class="grid g-gutter-x">
        
        <div class="g-col-lg-8">
            
            <div class="grid g-gutter">
                
                <div class="g-col-md-4">
                    <div class="facet facet--invert">
                        <div class="facet__header" data-cc-toggle-action="toggle" data-cc-toggle-target="#footer-facet-1" id="footer-facet-1-header" data-cc-toggle-group="footer-facet-header">
                            <h4><?php echo $this->__('We accept'); ?></h4>
                            <span class="facet__icon u-hidden-md u-hidden-lg u-hidden-xl"></span>
                        </div>
                        <div class="facet__body u-toggle-xs u-toggle-sm" id="footer-facet-1" data-cc-toggle-group="footer-facet" data-cc-toggle-target-callback="#footer-facet-1-header">
                            <?php echo $this->getChildHtml('payment_icons'); ?>
                        </div>
                    </div>
                    
                </div>
                
                <div class="g-col-md-4">
                    <?php echo $this->getChildHtml('footer_links_company'); ?>
                </div>
                
                <div class="g-col-md-4">
                    <?php echo $this->getChildHtml('footer_links_info'); ?>
                </div>
                
            </div>
            
        </div>
        
        <div class="g-col-lg-4">
            <?php echo $this->getChildHtml('company_blurb'); ?>
        </div>
        
    </div>
</div>