<div class="toggle-icon" data-cc-toggle-action="toggle" data-cc-toggle-target="#footer-4" id="footer-4-header" data-cc-toggle-group="footer-header">
    <h4>About Company</h4>
    <span class="toggle-icon__icon u-hidden-md u-hidden-lg u-hidden-xl"></span>
</div>
<div class="u-toggle-xs u-toggle-sm" id="footer-4" data-cc-toggle-group="footer-content" data-cc-toggle-target-callback="#footer-4-header">
    <p>Founded in 2003, we are a top company.</p>
    <div class="u-toggle" id="co-blurb">
        <p>company blurb to add</p>
        <p>For more information about us, visit our <a href="#">About Us</a> page.</p>
    </div>
    <p><a href="#" data-cc-toggle-action="toggle" data-cc-toggle-target="#co-blurb">Read more</a></p>
</div>