<div class="facet facet--invert">
    <div class="facet__header" data-cc-toggle-action="toggle" data-cc-toggle-target="#footer-facet-4" id="footer-facet-4-header" data-cc-toggle-group="footer-facet-header">
        <h4>About Company</h4>
        <span class="facet__icon u-hidden-md u-hidden-lg u-hidden-xl"></span>
    </div>
    <div class="facet__body u-toggle-xs u-toggle-sm" id="footer-facet-4" data-cc-toggle-group="footer-facet" data-cc-toggle-target-callback="#footer-facet-4-header">
        <p>Founded in 2003, we are a top company.</p>
        <div class="u-toggle" id="co-blurb">
            <p>company blurb to add</p>
            <p>For more information about us, visit our <a href="#">About Us</a> page.</p>
        </div>
        <p><a href="#" data-cc-toggle-action="toggle" data-cc-toggle-target="#co-blurb">Read more</a></p>
    </div>
</div>