<div class="facet facet--invert">
    <div class="facet__header is-active" data-cc-toggle-action="toggle" data-cc-toggle-target="#footer-facet-2" id="footer-facet-2-header" data-cc-toggle-group="footer-facet-header">
        <h4>Company</h4>
        <span class="facet__icon u-hidden-md u-hidden-lg u-hidden-xl"></span>
    </div>
    <div class="facet__body is-active u-toggle-xs u-toggle-sm" id="footer-facet-2" data-cc-toggle-group="footer-facet" data-cc-toggle-target-callback="#footer-facet-2-header">
        <ul class="nav nav--space">
            <li><a href="/about-us/">About Us</a></li>
            <li><a href="/blog/">Blog</a></li>
            <li><a href="/affiliates/">Affiliates</a></li>
            <li><a href="/contacts/">Contact Us</a></li>
        </ul>
    </div>
</div>