<div class="toggle-icon is-active" data-cc-toggle-action="toggle" data-cc-toggle-target="#footer-2" id="footer-2-header" data-cc-toggle-group="footer-header">
    <h4>Company</h4>
    <span class="toggle-icon__icon u-hidden-md u-hidden-lg u-hidden-xl"></span>
</div>
<div class="is-active u-toggle-xs u-toggle-sm" id="footer-2" data-cc-toggle-group="footer-content" data-cc-toggle-target-callback="#footer-2-header">
    <ul class="nav nav--space">
        <li><a href="/about-us/">About Us</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/affiliates/">Affiliates</a></li>
        <li><a href="/contacts/">Contact Us</a></li>
    </ul>
</div>