<div class="facet facet--invert">
    <div class="facet__header" data-cc-toggle-action="toggle" data-cc-toggle-target="#footer-facet-3" id="footer-facet-3-header" data-cc-toggle-group="footer-facet-header">
        <h4>Your account</h4>
        <span class="facet__icon u-hidden-md u-hidden-lg u-hidden-xl"></span>
    </div>
    <div class="facet__body u-toggle-xs u-toggle-sm" id="footer-facet-3" data-cc-toggle-group="footer-facet" data-cc-toggle-target-callback="#footer-facet-3-header">
        <ul class="nav nav--space">
            <li><a href="/terms-conditions/">Terms &amp; Conditions</a></li>
            <li><a href="/privacy/">Privacy Policy</a></li>
            <li><a href="/delivery/">Delivery</a></li>
            <li><a href="/returns/">Returns</a></li>
            <li><a href="/customer/account/">Order Status</a></li>
            <li><a href="/customer/account/login/">Sign in</a></li>
        </ul>
    </div>
</div>