<?php if ($this->getTitle() || $this->getDeactivateTarget()) : ?>
<hgroup class="title title--drawer">
    <p class="title__main h2"><?php echo $this->getTitle(); ?></p>
    <a href="#" class="title__btn btn btn--icon btn--invert btn--close" data-cc-action="deactivate" data-cc-target="<?php echo $this->getDeactivateTarget(); ?>"><?php echo Mage::helper('iweb_core/icons')->getSvg('custom--close'); ?></a>
</hgroup>
<?php endif; ?>