<div class="modal <?php echo $this->getModalSize(); ?>" id="modal" data-cc-cascade="overlay" data-cc-action="deactivate" data-cc-target="modal" data-cc-trigger-on="direct-only">
    <?php if($this->getShowModalClose()) : ?>
        <a href="#" data-cc-action="deactivate" data-cc-target="modal" class="btn btn--sm btn--close">
            <span class="shape-cross"></span>
            <span class="btn__text"><?php echo $this->__('Close'); ?></span>
        </a>
    <?php endif; ?>
    <div class="modal__dialog u-fill-grey-lighter">
        <?php echo $this->getChildHtml('modal'); ?>
    </div>
</div>