<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<header class="header">

    <a href="#" class="btn" data-cc-target="drawer-left" data-cc-action="activate">
        <span><?php echo $this->__('Menu'); ?></span>
        <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'menu'); ?>
    </a>
    
    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
        <picture>
            <source media="(max-width: 25.99em)" srcset="<?php echo $this->getLogoSrcSmall() ?>">
            <img src="<?php echo $this->getLogoSrc() ?>" class="logo__img" width="305" height="50" alt="<?php echo $this->getLogoAlt() ?>" />
        </picture>
    </a>
    
    <?php echo $this->getChildHtml('topSearch') ?>
    
    <a href="#" class="btn">
        <span><?php echo $this->__('Search'); ?></span>
        <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'search3'); ?>
    </a>
    
    <a href="<?php echo Mage::getUrl('customer/account'); ?>" class="btn">
        <span><?php echo $this->__('My Account'); ?></span>
        <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'user'); ?>
    </a>
    
    <a href="<?php echo Mage::getUrl('checkout/cart'); ?>" class="btn" data-cc-target="drawer-right">
        <span><?php echo $this->__('My Cart'); ?></span>
        <?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'cart'); ?>
    </a>
    
    <?php /* confidence used on checkout */ ?>
    <?php echo $this->getChildHtml('confidence') ?>
    
    <?php echo $this->getChildHtml('topMenu') ?>
    
</header>