<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <?php if($this->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

    <?php if($this->getShowAmounts()): ?>
    <div class="amount u-visually-hidden">
        <?php if($this->getLastPageNum()>1): ?>
            <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
        <?php else: ?>
            <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </div>
    <?php endif; ?>

    <?php if($this->getShowPerPage()): ?>
    <div class="limiter">
        <label class="u-visually-hidden"><?php echo $this->__('Show') ?></label>
        <select onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                <?php echo $_limit ?>
            </option>
        <?php endforeach; ?>
        </select>
        <span class="u-visually-hidden"><?php echo $this->__('per page') ?></span>
    </div>
    <?php endif ?>

    <?php if($this->getLastPageNum()>1): ?>
    <nav class="pagination pages">
        <ul class="nav nav--inline nav--pills nav--space">
            <li>
            <?php
            $firstStateClass = "";
            if ($this->isFirstPage()) :
                $firstStateClass = "is-disabled ";
            endif;
            ?>
                <a aria-label="<?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?>" class="<?php echo $firstStateClass; ?>previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?> pagination__previous" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?>">
                    <span class="u-visually-hidden"><?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?></span>
                </a>
            </li>
          
        <?php if ($this->canShowFirst()): ?>
            <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif;?>

        <?php if ($this->canShowPreviousJump()): ?>
            <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif;?>
        
        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="current"><a href="#" class="is-active"><?php echo $_page ?></a></li>
            <?php else: ?>
                <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>
        
        <?php if ($this->canShowNextJump()): ?>
            <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
        <?php endif;?>
        
        <?php if ($this->canShowLast()): ?>
            <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>
        
            <li>
                <?php
                $lastStateClass = "";
                if ($this->isLastPage()) :
                    $lastStateClass = "is-disabled ";
                endif;
                ?>
                <a aria-label="<?php echo Mage::helper('core')->quoteEscape($this->__('Next')) ?>" class="<?php echo $lastStateClass; ?>next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?> pagination__next" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Next')) ?>">
                    <span class="u-visually-hidden"><?php echo Mage::helper('core')->quoteEscape($this->__('Next')) ?></span>
                </a>
            </li>
      </ul>
    </nav>
    <?php endif; ?>
    

    <?php if($this->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>
