<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <?php if($this->getShowAmounts()): ?>
    <div class="amount">
        <?php if($this->getLastPageNum()>1): ?>
            <strong><?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?></strong>
        <?php else: ?>
            <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </div>
    <?php endif ?>

    <?php if($this->getShowPerPage()): ?>
    <div class="limiter grid g-gutter-x-sm g-collapse">
        <div>
            <label><?php echo $this->__('Show') ?></label>
        </div>
        <div>
            <select onchange="setLocation(this.value)">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="u-hidden-xs">
            <label><?php echo $this->__('per page') ?></label>
        </div>
    </div>
    <?php endif ?>

    <?php if($this->getLastPageNum()>1): ?>
    <nav class="pages pagination">
        <strong class="u-visually-hidden"><?php echo $this->__('Page:') ?></strong>
        <ol class="nav nav--inline nav--space">
        <?php if (!$this->isFirstPage()): ?>
            <li class="is-first nav__paged">
                <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?>">
                    <?php if(!$this->getAnchorTextForPrevious()): ?>
                        <?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?> <span class="u-hidden-xs"><?php echo $this->__('page'); ?></span>
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForPrevious() ?>
                    <?php endif;?>
                </a>
            </li>
        <?php endif;?>

        <?php if ($this->canShowFirst()): ?>
            <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif;?>

        <?php if ($this->canShowPreviousJump()): ?>
            <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="current is-active"><a href="#" class="is-active"><?php echo $_page ?></a></li>
            <?php else: ?>
                <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>


        <?php if ($this->canShowNextJump()): ?>
            <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php if ($this->canShowLast()): ?>
          <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>

        <?php if (!$this->isLastPage()): ?>
            <li class="is-last nav__paged">
                <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Next')) ?>">
                    <?php if(!$this->getAnchorTextForNext()): ?>
                        <?php echo Mage::helper('core')->quoteEscape($this->__('Next')) ?> <span class="u-hidden-xs"><?php echo $this->__('page'); ?></span>
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForNext() ?>
                    <?php endif;?>
                </a>
            </li>
        <?php endif;?>
        </ol>

    </nav>
    <?php endif; ?>

<?php endif ?>
