<ul class="u-list-inline">
    <li><img src="<?php echo Mage::helper('chopchop/icon')->getPaymentSvgPath('white', 'maestro'); ?>" alt="Maestro" width="63" height="40"></li>
    <li><img src="<?php echo Mage::helper('chopchop/icon')->getPaymentSvgPath('white', 'mastercard-securecode'); ?>" alt="Mastercard Securecode" width="63" height="40"></li>
    <li><img src="<?php echo Mage::helper('chopchop/icon')->getPaymentSvgPath('white', 'mastercard'); ?>" alt="Mastercard" width="63" height="40"></li>
    <li><img src="<?php echo Mage::helper('chopchop/icon')->getPaymentSvgPath('white', 'verified-by-visa'); ?>" alt="Verified By Visa" width="63" height="40"></li>
    <li><img src="<?php echo Mage::helper('chopchop/icon')->getPaymentSvgPath('white', 'paypal'); ?>" alt="Paypal" width="63" height="40"></li>
    <li><img src="<?php echo Mage::helper('chopchop/icon')->getPaymentSvgPath('white', 'sage'); ?>" alt="Sage" width="63" height="40"></li>
</ul>