<ul class="u-list-inline">
    <li><img src="/html/../build/img/icons/intermediate-svg/payments--white--paypal.svg" alt="Paypal" width="63" height="40"></li>
    <li><img src="/html/../build/img/icons/intermediate-svg/payments--white--visa.svg" alt="Visa" width="63" height="40"></li>
    <li><img src="/html/../build/img/icons/intermediate-svg/payments--white--mastercard-securecode.svg" alt="Mastercard Securecode" width="63" height="40"></li>
    <li><img src="/html/../build/img/icons/intermediate-svg/payments--white--maestro.svg" alt="Maestro" width="63" height="40"></li>
    <li><img src="/html/../build/img/icons/intermediate-svg/payments--white--mastercard.svg" alt="Mastercard" width="63" height="40"></li>
    <li><img src="/html/../build/img/icons/intermediate-svg/payments--white--verified-by-visa.svg" alt="Verified By Visa" width="63" height="40"></li>
    <li><img src="/html/../build/img/icons/intermediate-svg/payments--white--american-express.svg" alt="America Express" width="63" height="40"></li>
</ul>