<ul class="u-list-inline">
    <li><?php echo Mage::helper('chopchop/icon')->getSvgHtml('card', 'Visa-card-light', 'icon--card'); ?></li>
    <li><?php echo Mage::helper('chopchop/icon')->getSvgHtml('card', 'MasterCard-light', 'icon--card'); ?></li>
    <li><?php echo Mage::helper('chopchop/icon')->getSvgHtml('card', 'Maestro-card-light', 'icon--card'); ?></li>
    <li><?php echo Mage::helper('chopchop/icon')->getSvgHtml('payment', 'Apple-card-light', 'icon--card'); ?></li>
    <li><?php echo Mage::helper('chopchop/icon')->getSvgHtml('payment', 'Paypal-card-light', 'icon--card'); ?></li>
    <li><?php echo Mage::helper('chopchop/icon')->getSvgHtml('payment', 'Sage-card-light', 'icon--card'); ?></li>
</ul>