<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table class="data-table table" id="checkout-review-table">
        <thead>
            <tr>
                <th ><?php echo $this->__('Product Name') ?></th>
                <th class="a-center"><?php echo $this->__('Price') ?></th>
                <th class="a-center"><?php echo $this->__('Qty') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
    
    <table id="checkout-review-totals-table">
        <?php echo $this->getChildHtml('totals'); ?>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit">
    <hr />
    <?php echo $this->getChildHtml('agreements') ?>
    
    <div class="buttons-set grid g-gutter" id="review-buttons-container">
        <div class="g-col-sm-6 g-col-lg-5">
            <?php echo $this->getChildHtml('button') ?>
        </div>
        <div class="g-col-sm-6 g-col-lg-7">
            <span class="micro"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></span>
        </div>
        <div class="g-col-xs-12">
            <span class="loading" id="review-please-wait" style="display:none;">
                <span class="u-shape-ring u-spin"></span>
                <span class="loading__text"><?php echo $this->__('Submitting order information...') ?></span>
            </span>
        </div>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>
