<div class="bordered-box u-clearfix u-section-xs-bottom">
    <div class="u-container u-section-xs">
        <h3><?php echo $this->__('Total'); ?></h3>
        <table id="order-summary-totals-table">
            <?php echo $this->getChildHtml('totals'); ?>
        </table>
        <?php echo $this->getChildHtml('checkout.cart.methods'); ?>
        <?php echo $this->getChildHtml('coupon') ?>
    </div>
</div>