<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="cart-cell">
    <?php //echo $this->getPriceHtml($product, empty($options));?>
    
    <div class="add-to-cart-alt inline-form u-mw-10">
        <?php if ($product->isSaleable()): ?>

            <?php if ($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()): ?>
                <input type="text" class="input-text input--sm qty validate-not-negative-number" data-type="number" name="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" />
            <?php endif; ?>

        <?php else: ?>
            <?php //echo $this->getAddToCartQty($item) * 1 ?>&nbsp;
        <?php endif; ?>

        <?php if ($product->isSaleable()): ?>
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" onclick="addWItemToCart(<?php echo $item->getId()?>);" class="button btn-cart btn--wishlist-cart">
            <span><?php echo $this->__('Add') ?></span>
        </button>
        <?php else: ?>
            <?php if ($product->getIsSalable()): ?>
            <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
        <?php endif; ?>

    </div>
    
    <div class="cart-links">
        <a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Delete')) ?>" class="btn--wishlist-remove btn-remove2 remove-button"><?php echo $this->__('Delete');?></a>
    
    <?php foreach($this->getSortedChildren() as $childName):?>
        <?php echo $this->getChildHtml($childName, false);?>
    <?php endforeach;?>

    <?php /*if ($product->isVisibleInSiteVisibility()): ?>
        <a class="link-edit btn" href="<?php echo $this->getItemConfigureUrl($item) ?>"><?php echo $this->__('Edit') ?></a>
    <?php endif */?>
    </div>

</div>