<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>

<?php echo $this->getPagerHtml(); ?>


<?php if($_orders->getSize()): ?>
<table class="data-table" id="my-orders-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Ship To') ?></th>
            <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
        <tr>
            <td data-label="<?php echo $this->__('Order #') ?>"><?php echo $_order->getRealOrderId() ?></td>
            <td data-label="<?php echo $this->__('Date') ?>"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
            <td data-label="<?php echo $this->__('Ship To') ?>"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td data-label="<?php echo $this->__('Order Total') ?>"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td data-label="<?php echo $this->__('Order Status') ?>"><em><?php echo $_order->getStatusLabel() ?></em></td>
            <td class="a-center full-width">
                <a href="<?php echo $this->getViewUrl($_order) ?>" class="button btn"><?php echo $this->__('View Order') ?></a>
                    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                    <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder button btn"><?php echo $this->__('Reorder') ?></a>
                <?php endif ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
