<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>

<div class="toolbar toolbar--top">
<?php echo $this->getPagerHtml(); ?>
</div>

<div class="card">
    
<?php if($_orders->getSize()): ?>
    <div class="card__body">
        <table class="data-table" id="my-orders-table">
            <thead>
                <tr>
                    <th><?php echo $this->__('Order #') ?></th>
                    <th><?php echo $this->__('Date') ?></th>
                    <th><?php echo $this->__('Ship To') ?></th>
                    <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php $_odd = ''; ?>
                <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td><?php echo $_order->getRealOrderId() ?></td>
                    <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-center">
                        <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>" class="btn--view-order"><?php echo $this->__('View Order') ?></a>
                            <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<script type="text/javascript">decorateTable('my-orders-table');</script>

<?php else: ?>
    <div class="card__body">
        <p><?php echo $this->__('You have placed no orders.'); ?></p>
    </div>
<?php endif ?>
</div>

<div class="toolbar toolbar--bottom">
<?php echo $this->getPagerHtml(); ?>
</div>