<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view o-product">
    
    <div class="o-product__aside">
        <div class="js-ph-img-big">
            <?php echo $this->getChildHtml('media') ?>
        </div>
        <?php echo $this->getChildHtml('related') ?>
    </div>
    
    <div class="o-product__content">
        
        <div class="o-product-essential">
            
            <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <?php echo $this->getBlockHtml('formkey') ?>
                <div class="no-display u-hidden">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>
                <hgroup class="title title--link">
                    <div class="title__titles">
                        <h1 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>
                </hgroup>
                
                <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getTierPriceHtml() ?>
                <?php echo $this->getChildHtml('extrahint') ?>
                
                <?php if (!$this->hasOptions()):?>
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                    <?php echo $this->getChildHtml('addto') ?>
                <?php endif; ?>
                
                <?php if ($this->canEmailToFriend()): ?>
                <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="btn btn--text">
                    <?php echo $this->__('Email to a Friend') ?>
                </a>
                <?php endif; ?>
                
                <?php echo $this->getChildHtml('other');?>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>
                
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
            </form>
            
        </div><!--/o-product-essential-->

        <div class="product-collateral">

            <div class="accordion-to-tabs o-product-tabs" data-cc-collapse="one-open">
                <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
                <?php if ($title = $this->getChildData($alias, 'title')):?>
                <div class="tabs__header" id="tabs-header-<?php echo "box-{$alias}"?>" data-cc-group="tabs1-header" data-cc-action="activate" data-cc-target="tabs-<?php echo "box-{$alias}"?>">
                    <h4><?php echo $this->escapeHtml($title); ?></h4>
                    <span class="shape"></span>
                </div>
                <?php endif;?>
                <div class="tabs__body" id="tabs-<?php echo "box-{$alias}"?>" data-cc-group="tabs1-content" data-cc-cascade-activate="tabs-header-<?php echo "box-{$alias}"?>">
                    <?php echo $html; ?>
                </div>
                <?php endforeach;?>
            </div>

        </div>

    </div><!--o-product--content -->
    
    
</div>



<?php echo $this->getChildHtml('upsell_products') ?>
<?php echo $this->getChildHtml('product_additional_data') ?>

<script type="text/javascript">
//<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
               form.action = url;
            }
            var e = null;
            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
//]]>
</script>