<?php $_storePhone = Mage::getStoreConfig('general/store_information/phone'); ?>
<div class="u-section-sm">
    <div class="grid g-gutter-x-lg">
        <div class="g-col-sm-6 g-col-md-3">
            <div>
                <h4><?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'phone2'); ?> Help</h4>
                <p>
                    Call us: <?php echo $_storePhone; ?><br />
                    Mon-Fri: 8am-8pm<br />
                    Sat-Sun: 10am-6pm<br />
                    Bank Holidays: 10am-6pm
                </p>
            </div>
        </div>
        <div class="g-col-sm-6 g-col-md-3">
            <div>
                <h4><?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'lock4'); ?> Security</h4>
                <p>
                    Secure payment: Our systems are protected by <strong>Thawte</strong>, the leading  Secure Sockets Layer (SSL) authority.
                </p>
            </div>
        </div>
        <div class="g-col-sm-6 g-col-md-3">
            <div>
                <h4><?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'lock4'); ?> Delivery</h4>
                <p>
                    Real time tracking: Track the progress of your order in real time via the My Account section.
                </p>
            </div>
        </div>
        <div class="g-col-sm-6 g-col-md-3">
            <div>
                <h4><?php echo Mage::helper('chopchop/icon')->getSvgHtml('general', 'lock4'); ?> Returns</h4>
                <p>
                    Returns policy: If you don't like what you've bought, just let us know within 14 days, and we'll return your money.
                </p>
            </div>
        </div>
    </div>
</div>