<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <div class="quantity quantity--center js-qty">
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <div class="quantity__amount">
                <a href="#" class="btn btn--icon btn--square">
                    <?php echo Mage::helper('iweb_core/icons')->getSvg('custom--minus'); ?>
                    <span class="u-visually-hidden"><?php echo $this->__('Decrease quantity'); ?></span>
                </a>
                <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" min="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty u-text-center" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" />
                <a href="#" class="btn btn--icon btn--square">
                    <?php echo Mage::helper('iweb_core/icons')->getSvg('custom--plus'); ?>
                    <span class="u-visually-hidden"><?php echo $this->__('Increase quantity'); ?></span>
                </a>
            </div>
        </div>
        
        <script type="text/javascript">
        (function($){
            var qtyWidget = new Iweb.QtyWidget({
                'delegateContainerSelector':'.js-qty',
                'minQty': 1
            });
        }(jQuery));
        </script>

        <?php endif; ?>
        
        <p class="micro" todo><strong>Earn 10 TONU™ Reward Points</strong></p>
        
        <p><button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn-cart btn btn--primary btn--arrow btn--xl" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button></p>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
