<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>

    
    <div class="grid g-gutter g-stretch-first g-center-y">
        <div>
            <h2><?php echo $this->__('New Products') ?></h2>
        </div>
    </div>

    <div class="scroll js-scroll is-start">
        <a href="#" class="scroll__arrow scroll__arrow--left"></a>
        <a href="#" class="scroll__arrow scroll__arrow--right"></a>
        
        <div class="scroll__container js-scroll__container">
            <div class="scroll__body">
    <?php //echo $this->getPagerHtml() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <div>
            <div class="product-item">
                <div class="product-item__image">
                    <div class="layer">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220) ?>" width="220" height="220" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="u-center" /></a>
                    </div>
                </div>
                <div class="product-item__body">
                    <div><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></div>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                </div>
                <div class="product-item__footer">
                    <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                    <?php if ($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart btn--block" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
                
                <div class="u-hidden">
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
                
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
</div>
</div>
<?php endif; ?>
