<!-- [start] center -->
    <div id="main" class="col-main">
    <!-- [start] content -->
        <div class="title">
            <h2 class="title__main">503 error</h2>
            <h3 class="title__sub u-highlight-brand-pink"><span>Service Temporarily Unavailable</span></h3>
        </div>
        <div class="u-section-sm">
            <p>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.</p>
        </div>
    <!-- [end] content -->
    </div>
<!-- [end] center -->
