<!DOCTYPE html>
<html lang="en">
<head>
<title><?php echo $this->pageTitle?></title>
<base href="<?php echo $this->getSkinUrl()?>" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="*" />
<link rel="stylesheet" href="css/normalize.css" type="text/css" />
<link rel="stylesheet" href="css/styles.css" type="text/css" />
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<style>
body {
    height: 90vh;
    margin-top: 5vh;
    margin-bottom: 5vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
}
</style>
</head>
<body>
    <div class="u-container-sm">
        <h1>
            <a href="<?php echo $this->getBaseUrl()?>" class="logo">
                <img src="images/logo.svg" width="200" height="50" />
                <span class="u-visually-hidden">Site Name Here</span>
            </a>
        </h1>
        <?php require_once $contentTemplate; ?>
        <p class="micro">Copyright &copy; 2017 Site Name Here. All Rights Reserved.</p>
    </div>
</body>
</html>
