<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('header') ?>
<?php echo $this->getChildHtml('before_main') ?>
<div class="main-container col2-right-layout">
    <?php echo $this->getChildHtml('breadcrumbs') ?>
    
    <div class="main u-section-sm-top u-section-lg-bottom <?php echo $this->getContainerClass(); ?>">
        <div class="<?php echo $this->getContainerClasses(); ?>">
            <div class="grid g-gutter">
                <div class="col-main <?php echo $this->getMainClasses(); ?>">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('before_content') ?>
                    <?php echo $this->getChildHtml('content') ?>
                    <?php echo $this->getChildHtml('after_content') ?>
                </div>
                <div class="col-right sidebar <?php echo $this->getRightSidebarClasses(); ?>">
                    <?php echo $this->getChildHtml('right') ?>
                </div>
            </div>
        </div>
    </div>
    
</div>
<?php echo $this->getChildHtml('after_main') ?>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>