<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('header') ?>
<?php echo $this->getChildHtml('before_main') ?>
<div class="main-container col3-layout">
    <div class="main <?php echo $this->getContainerClass(); ?>">
        <?php echo $this->getChildHtml('breadcrumbs') ?>
        <?php echo $this->getChildHtml('before_content') ?>
        <div class="l-three-col-alternate l-gutter col-wrapper">
            <div class="l-body col-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
            <div class="l-side col-left sidebar">
                <?php echo $this->getChildHtml('left') ?>
            </div>
            <div class="l-side l-side--right col-right sidebar">
                <?php echo $this->getChildHtml('right') ?>
            </div>
        </div>
        <?php echo $this->getChildHtml('after_content') ?>
    </div>
</div>
<?php echo $this->getChildHtml('after_main') ?>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>