<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login">
    
    <hgroup class="title">
        <div class="title__headings">
            <h1 class="title__main"><?php echo $this->__('Login or Create an Account') ?></h1>
            <h3 class="title__sub"><?php echo $this->__('Welcome to Aqua Cure') ?></h3>
        </div>
    </hgroup>
    
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col2-set o-customer-login">
            <div class="col-1 new-users">
                <div class="content card--customer-login">
                    <div class="card__header">
                        <h2 class="card__title"><?php echo $this->__('New Customers') ?></h2>
                        <span></span>
                    </div>
                    <div class="card__body">
                        <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                    </div>
                    <div class="buttons-set card__footer">
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Create an Account')) ?>" class="button btn--create-account" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                        <span></span>
                    </div>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="content card--customer-login">
                    <div class="card__header">
                        <h2 class="card__title"><?php echo $this->__('Registered Customers') ?></h2>
                        <span class="help-text required"><?php echo $this->__('* Required Fields') ?></span>
                    </div>
                    <div class="card__body">
                        <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                        <ul class="form-list">
                            <li class="field-group field-group--scaffold">
                                <label for="email" class="field-group__label required"><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box field-group__field">
                                    <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
                                </div>
                            </li>
                            <li class="field-group field-group--scaffold">
                                <label for="pass" class="field-group__label required"><?php echo $this->__('Password') ?></label>
                                <div class="input-box field-group__field">
                                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    </div>
                    <div class="buttons-set card__footer">
                        <button type="submit" class="button btn--login" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>" name="send" id="send2">
                            <span><span><?php echo $this->__('Login') ?></span></span>
                        </button>
                        <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left btn--forgot-password"><?php echo $this->__('Forgot Your Password?') ?></a>
                    </div>
                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
