<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
    
    <div class="col2-set grid g-gutter g-reverse">
        <div class="col-1 g-col-md-6 new-users">
            <div class="card">
                <div class="card__header">
                    <h2 class="h3"><?php echo $this->__('New Customers') ?></h2>
                </div>
                <div class="card__body">
                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                </div>
                <div class="card__footer buttons-set">
                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Create an Account')) ?>" class="button" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                </div>
            </div>
        </div>
        <div class="col-2 g-col-md-6 registered-users">
            <?php echo $this->getChildHtml('login_form'); ?>
        </div>
    </div>
</div>
