<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Address Book') ?></h1>
    <p><button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add New Address')) ?>" class="button" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button></p>
</div>
<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <h2 class="h3"><?php echo $this->__('Default Addresses') ?></h2>
        <div class="grid g-gutter g-stretch">
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <div class="item g-col-md-6">
                <h3 class="h4"><?php echo $this->__('Default Billing Address') ?></h3>
                <address>
                    <p><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></p>
                </address>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>
           </div>
        <?php else: ?>
            <div class="item g-col-md-6">
                <h3 class="h4"><?php echo $this->__('Default Billing Address') ?></h3>
                <p><?php echo $this->__('You have no default billing address in your address book.') ?></p>
            </div>
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <div class="item g-col-md-6">
                <h3 class="h4"><?php echo $this->__('Default Shipping Address') ?></h3>
                <address>
                    <p><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></p>
                </address>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>
            </div>
        <?php else: ?>
            <div class="item g-col-md-6 empty">
                <h3 class="h4"><?php echo $this->__('Default Shipping Address') ?></h3>
                <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            </div>
        <?php endif ?>
        </div>
    </div>
    <div class="col-2 addresses-additional">
        <h2 class="h3"><?php echo $this->__('Additional Address Entries') ?></h2>
        <div>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <div class="item g-col-md-6">
                <address>
                    <p><?php echo $this->getAddressHtml($_address) ?></p>
                </address>
                <p><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a></p>
            </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="item empty">
                <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
            </div>
        <?php endif ?>
        </div>
    </div>
</div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to delete this address?')) ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
