<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>
<?php if($this->getTitle()): ?>
<div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="card--customer-address-edit">
    <form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey')?>
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <div class="card__header">
                <h2 class="legend card__title"><?php echo $this->__('Contact Information') ?></h2>
            </div>
            <div class="card__body">
                <ul class="form-list">
                    <li class="fields">
                        <?php echo $this->getNameBlockHtml() ?>
                    </li>
                    <li class="wide">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="telephone" class="required"><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="fax"><?php echo $this->__('Fax') ?></label>
                            <div class="input-box">
                                <input type="text" name="fax" id="fax" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Fax')) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="fieldset">
            <div class="card__header">
                <h2 class="legend card__title"><?php echo $this->__('Address') ?></h2>
            </div>
            <div class="card__body">
                <ul class="form-list">
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="street_1" class="required"><?php echo $this->__('Street Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide">
                        <label for="street_<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
                <?php endfor; ?>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                        <div class="input-box">
                            <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')) ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="city" class="required"><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="region_id" class="required"><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                   <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="zip" class="required"><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="u-mw-10 input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="country" class="required"><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect() ?>
                            </div>
                        </div>
                    </li>
                    <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control field-group field-group--inline""' ?>>
                        <?php if($this->isDefaultBilling()): ?>
                            <strong><?php echo $this->__('Default Billing Address') ?></strong>
                        <?php elseif($this->canSetAsDefaultBilling()): ?>
                            <div class="field-group__field">
                                <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Billing Address')) ?>" class="checkbox" />
                            </div>
                            <div class="field-group__label">
                                <label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                            </div>
                        <?php else: ?>
                            <input type="hidden" name="default_billing" value="1" />
                        <?php endif; ?>
                    </li>
                    <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control field-group field-group--inline""' ?>>
                        <?php if($this->isDefaultShipping()): ?>
                            <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                        <?php elseif($this->canSetAsDefaultShipping()): ?>
                            <div class="field-group__field">
                                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Shipping Address')) ?>" class="checkbox" />
                            </div>
                            <div class="field-group__label">
                                <label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                            </div>
                        <?php else: ?>
                            <input type="hidden" name="default_shipping" value="1" />
                        <?php endif; ?>
                    </li>
                </ul>
            </div>
        </div>
        <div class="buttons-set card__footer">
            <button data-action="save-customer-address" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>" class="button btn--customer-save-address"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
            <span class="help-text required"><?php echo $this->__('* Required Fields') ?></span>
        </div>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
//]]>
</script>
